// Generated by tools/gen_sounds.py from its CUES table. Do not edit by hand:
// change the table and re-run the script, which rewrites this file and the
// WAVs together.
//
// Every pulse is one haptic and the notes that start with it, so the sound
// of a cue and its haptic pattern are written from the same numbers.

export type HapticStyle = 'selection' | 'soft' | 'light' | 'medium' | 'rigid' | 'heavy';

export type Pulse = readonly [ms: number, haptic: HapticStyle];

export const CUES = {
  tick: {
    file: require('../../assets/sounds/tick.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  detent: {
    file: require('../../assets/sounds/detent.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  advance: {
    file: require('../../assets/sounds/advance.wav'),
    pulses: [[0, 'light']] as readonly Pulse[],
  },
  commit: {
    file: require('../../assets/sounds/commit.wav'),
    pulses: [
      [0, 'rigid'],
      [70, 'medium'],
    ] as readonly Pulse[],
  },
  correct0: {
    file: require('../../assets/sounds/correct0.wav'),
    pulses: [
      [0, 'light'],
      [95, 'rigid'],
    ] as readonly Pulse[],
  },
  correct1: {
    file: require('../../assets/sounds/correct1.wav'),
    pulses: [
      [0, 'light'],
      [95, 'rigid'],
    ] as readonly Pulse[],
  },
  streak: {
    file: require('../../assets/sounds/streak.wav'),
    pulses: [
      [0, 'light'],
      [80, 'light'],
      [160, 'medium'],
    ] as readonly Pulse[],
  },
  amber: {
    file: require('../../assets/sounds/amber.wav'),
    pulses: [[0, 'soft']] as readonly Pulse[],
  },
  wrong: {
    file: require('../../assets/sounds/wrong.wav'),
    pulses: [
      [0, 'medium'],
      [170, 'soft'],
    ] as readonly Pulse[],
  },
  pop0: {
    file: require('../../assets/sounds/pop0.wav'),
    pulses: [[0, 'light']] as readonly Pulse[],
  },
  pop1: {
    file: require('../../assets/sounds/pop1.wav'),
    pulses: [[0, 'light']] as readonly Pulse[],
  },
  pop2: {
    file: require('../../assets/sounds/pop2.wav'),
    pulses: [[0, 'light']] as readonly Pulse[],
  },
  pop3: {
    file: require('../../assets/sounds/pop3.wav'),
    pulses: [[0, 'light']] as readonly Pulse[],
  },
  miss: {
    file: require('../../assets/sounds/miss.wav'),
    pulses: [[0, 'rigid']] as readonly Pulse[],
  },
  note0: {
    file: require('../../assets/sounds/note0.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note1: {
    file: require('../../assets/sounds/note1.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note2: {
    file: require('../../assets/sounds/note2.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note3: {
    file: require('../../assets/sounds/note3.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note4: {
    file: require('../../assets/sounds/note4.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note5: {
    file: require('../../assets/sounds/note5.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note6: {
    file: require('../../assets/sounds/note6.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note7: {
    file: require('../../assets/sounds/note7.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note8: {
    file: require('../../assets/sounds/note8.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  note9: {
    file: require('../../assets/sounds/note9.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  coin: {
    file: require('../../assets/sounds/coin.wav'),
    pulses: [[0, 'selection']] as readonly Pulse[],
  },
  complete: {
    file: require('../../assets/sounds/complete.wav'),
    pulses: [
      [0, 'heavy'],
      [110, 'light'],
      [220, 'light'],
      [330, 'light'],
    ] as readonly Pulse[],
  },
  perfect: {
    file: require('../../assets/sounds/perfect.wav'),
    pulses: [
      [0, 'heavy'],
      [100, 'light'],
      [200, 'light'],
      [300, 'light'],
      [420, 'rigid'],
    ] as readonly Pulse[],
  },
  badge: {
    file: require('../../assets/sounds/badge.wav'),
    pulses: [
      [0, 'heavy'],
      [180, 'light'],
    ] as readonly Pulse[],
  },
  unlock: {
    file: require('../../assets/sounds/unlock.wav'),
    pulses: [
      [0, 'light'],
      [110, 'rigid'],
    ] as readonly Pulse[],
  },
  tier: {
    file: require('../../assets/sounds/tier.wav'),
    pulses: [
      [0, 'light'],
      [140, 'light'],
      [280, 'medium'],
      [440, 'heavy'],
      [620, 'light'],
    ] as readonly Pulse[],
  },
} as const;

export type CueName = keyof typeof CUES;
