#!/usr/bin/env node
// Writes src/content.generated.ts: one import per sub-level file under content/,
// grouped by chapter and in play order. src/content.ts builds the map from it,
// so a new lesson file is wired in by running `npm run gen:content`, not by
// hand-editing a list of imports (docs/build-plan.md, stage WIRE; M13, S38).
//
//   node tools/gen_content.mjs           write the index
//   node tools/gen_content.mjs --check   exit 1 if the index is out of date (CI)
//
// Which files count: every `level-NN-M.yaml` in `content/shared/chapter-*` and
// `content/paths/<path>/chapter-*`. Drill packs and the market profiles are not
// lessons. Order: shared chapters first, then each path in folder order, each
// chapter by folder name, each file by level number, then sub-level number.
// A chapter's bonus side lessons, `level-NN-bonus.yaml` (docs/schema.md, stage
// DESIGN-REVIEW), are listed apart, by the level they follow. The glossary,
// `content/glossary.yaml`, is imported when it exists (stage GLOSSARY).
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'content.generated.ts');
const FILE = /^level-(\d+)-(\d+)\.yaml$/;
const BONUS = /^level-(\d+)-bonus\.yaml$/;
const GLOSSARY = join(root, 'content', 'glossary.yaml');

const dirsIn = (dir) =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
    : [];

/** Every chapter folder: `{ path, folder }`, `path` being `all` for the shared ones. */
function chapters() {
  const found = [];
  for (const folder of dirsIn(join(root, 'content', 'shared'))) {
    if (folder.startsWith('chapter-')) found.push({ path: 'all', rel: `shared/${folder}` });
  }
  for (const path of dirsIn(join(root, 'content', 'paths'))) {
    for (const folder of dirsIn(join(root, 'content', 'paths', path))) {
      if (folder.startsWith('chapter-')) found.push({ path, rel: `paths/${path}/${folder}` });
    }
  }
  return found;
}

function filesOf(rel) {
  return readdirSync(join(root, 'content', rel))
    .map((name) => ({ name, m: FILE.exec(name) }))
    .filter((f) => f.m)
    .sort((a, b) => Number(a.m[1]) - Number(b.m[1]) || Number(a.m[2]) - Number(b.m[2]))
    .map((f) => f.name);
}

function bonusOf(rel) {
  return readdirSync(join(root, 'content', rel))
    .map((name) => ({ name, m: BONUS.exec(name) }))
    .filter((f) => f.m)
    .sort((a, b) => Number(a.m[1]) - Number(b.m[1]))
    .map((f) => f.name);
}

function render() {
  const imports = [];
  const groups = [];
  let n = 0;
  let b = 0;
  for (const { path, rel } of chapters()) {
    const names = [];
    for (const file of filesOf(rel)) {
      const name = `f${n++}`;
      imports.push(`import ${name} from '../content/${rel}/${file}';`);
      names.push(name);
    }
    const bonus = [];
    for (const file of bonusOf(rel)) {
      const name = `b${b++}`;
      imports.push(`import ${name} from '../content/${rel}/${file}';`);
      bonus.push(name);
    }
    if (names.length === 0) continue;
    groups.push(
      `  {\n    path: '${path}',\n    folder: '${rel}',\n    files: [${names.join(', ')}],\n    bonus: [${bonus.join(', ')}],\n  },`,
    );
  }
  const glossary = existsSync(GLOSSARY);
  if (glossary) imports.push("import glossary from '../content/glossary.yaml';");
  return [
    '// Generated by `npm run gen:content` (tools/gen_content.mjs) from content/**.',
    '// Do not edit by hand: CI fails when this file and content/ disagree.',
    ...imports,
    '',
    '/**',
    ' * Every chapter folder under content/, in map order, with its sub-level files',
    ' * in play order and its bonus side lessons by the level they follow.',
    ' */',
    'export const CHAPTER_FILES: {',
    '  path: string;',
    '  folder: string;',
    '  files: unknown[];',
    '  bonus: unknown[];',
    '}[] = [',
    ...groups,
    '];',
    '',
    '/** content/glossary.yaml, once stage GLOSSARY has written it. */',
    `export const GLOSSARY: unknown = ${glossary ? 'glossary' : 'null'};`,
    '',
  ].join('\n');
}

const text = render();
if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== text) {
    console.error(
      `${relative(root, out)} is out of date with content/. Run \`npm run gen:content\` and commit it.`,
    );
    process.exit(1);
  }
  console.log(`${relative(root, out)} is up to date.`);
} else {
  writeFileSync(out, text);
  const count = (text.match(/^import f/gm) || []).length;
  const bonus = (text.match(/^import b/gm) || []).length;
  console.log(`Wrote ${relative(root, out)}: ${count} sub-level files, ${bonus} bonus lessons.`);
}
