// Generated by `npm run gen:content` (tools/gen_content.mjs) from content/**.
// Do not edit by hand: CI fails when this file and content/ disagree.
import f0 from '../content/shared/chapter-01-market-basics/level-01-1.yaml';
import f1 from '../content/shared/chapter-01-market-basics/level-01-2.yaml';
import f2 from '../content/shared/chapter-01-market-basics/level-01-3.yaml';
import f3 from '../content/shared/chapter-01-market-basics/level-01-4.yaml';
import f4 from '../content/shared/chapter-01-market-basics/level-02-1.yaml';
import f5 from '../content/shared/chapter-01-market-basics/level-02-2.yaml';
import f6 from '../content/shared/chapter-01-market-basics/level-02-3.yaml';
import f7 from '../content/shared/chapter-01-market-basics/level-03-1.yaml';
import f8 from '../content/shared/chapter-01-market-basics/level-03-2.yaml';
import f9 from '../content/shared/chapter-01-market-basics/level-03-3.yaml';
import f10 from '../content/shared/chapter-01-market-basics/level-04-1.yaml';
import f11 from '../content/shared/chapter-01-market-basics/level-04-2.yaml';
import f12 from '../content/shared/chapter-01-market-basics/level-04-3.yaml';
import f13 from '../content/shared/chapter-01-market-basics/level-04-4.yaml';
import f14 from '../content/shared/chapter-01-market-basics/level-05-1.yaml';
import f15 from '../content/shared/chapter-01-market-basics/level-06-1.yaml';
import f16 from '../content/shared/chapter-01-market-basics/level-06-2.yaml';
import f17 from '../content/shared/chapter-01-market-basics/level-06-3.yaml';
import f18 from '../content/shared/chapter-01-market-basics/level-07-1.yaml';
import f19 from '../content/shared/chapter-01-market-basics/level-07-2.yaml';
import f20 from '../content/shared/chapter-01-market-basics/level-07-3.yaml';
import f21 from '../content/shared/chapter-01-market-basics/level-07-4.yaml';
import f22 from '../content/shared/chapter-01-market-basics/level-08-1.yaml';
import f23 from '../content/shared/chapter-01-market-basics/level-08-2.yaml';
import f24 from '../content/shared/chapter-01-market-basics/level-08-3.yaml';
import f25 from '../content/shared/chapter-01-market-basics/level-09-1.yaml';
import f26 from '../content/shared/chapter-01-market-basics/level-09-2.yaml';
import f27 from '../content/shared/chapter-01-market-basics/level-10-1.yaml';
import f28 from '../content/shared/chapter-01-market-basics/level-10-2.yaml';
import f29 from '../content/shared/chapter-01-market-basics/level-10-3.yaml';
import f30 from '../content/shared/chapter-01-market-basics/level-11-1.yaml';
import f31 from '../content/shared/chapter-01-market-basics/level-12-1.yaml';
import f32 from '../content/shared/chapter-01-market-basics/level-12-2.yaml';
import f33 from '../content/shared/chapter-01-market-basics/level-12-3.yaml';
import f34 from '../content/shared/chapter-01-market-basics/level-13-1.yaml';
import f35 from '../content/shared/chapter-01-market-basics/level-13-2.yaml';
import f36 from '../content/shared/chapter-01-market-basics/level-13-3.yaml';
import f37 from '../content/shared/chapter-01-market-basics/level-13-4.yaml';
import f38 from '../content/shared/chapter-01-market-basics/level-14-1.yaml';
import f39 from '../content/shared/chapter-01-market-basics/level-14-2.yaml';
import f40 from '../content/shared/chapter-01-market-basics/level-14-3.yaml';
import f41 from '../content/shared/chapter-01-market-basics/level-15-1.yaml';
import f42 from '../content/shared/chapter-01-market-basics/level-15-2.yaml';
import f43 from '../content/shared/chapter-01-market-basics/level-15-3.yaml';
import f44 from '../content/shared/chapter-01-market-basics/level-16-1.yaml';
import f45 from '../content/shared/chapter-01-market-basics/level-16-2.yaml';
import f46 from '../content/shared/chapter-01-market-basics/level-17-1.yaml';
import f47 from '../content/shared/chapter-01-market-basics/level-17-2.yaml';
import f48 from '../content/paths/scalping/chapter-02-charts-101/level-01-1.yaml';
import f49 from '../content/paths/scalping/chapter-02-charts-101/level-01-2.yaml';
import f50 from '../content/paths/scalping/chapter-02-charts-101/level-01-3.yaml';
import f51 from '../content/paths/scalping/chapter-02-charts-101/level-01-4.yaml';
import f52 from '../content/paths/scalping/chapter-02-charts-101/level-02-1.yaml';
import f53 from '../content/paths/scalping/chapter-02-charts-101/level-02-2.yaml';
import f54 from '../content/paths/scalping/chapter-02-charts-101/level-02-3.yaml';
import f55 from '../content/paths/scalping/chapter-02-charts-101/level-03-1.yaml';
import f56 from '../content/paths/scalping/chapter-02-charts-101/level-03-2.yaml';
import f57 from '../content/paths/scalping/chapter-02-charts-101/level-03-3.yaml';
import f58 from '../content/paths/scalping/chapter-02-charts-101/level-04-1.yaml';
import f59 from '../content/paths/scalping/chapter-02-charts-101/level-04-2.yaml';
import f60 from '../content/paths/scalping/chapter-02-charts-101/level-04-3.yaml';
import f61 from '../content/paths/scalping/chapter-02-charts-101/level-04-4.yaml';
import f62 from '../content/paths/scalping/chapter-02-charts-101/level-05-1.yaml';
import f63 from '../content/paths/scalping/chapter-02-charts-101/level-05-2.yaml';
import f64 from '../content/paths/scalping/chapter-02-charts-101/level-06-1.yaml';
import f65 from '../content/paths/scalping/chapter-02-charts-101/level-07-1.yaml';
import f66 from '../content/paths/scalping/chapter-02-charts-101/level-07-2.yaml';
import f67 from '../content/paths/scalping/chapter-02-charts-101/level-07-3.yaml';
import f68 from '../content/paths/scalping/chapter-02-charts-101/level-07-4.yaml';
import f69 from '../content/paths/scalping/chapter-02-charts-101/level-08-1.yaml';
import f70 from '../content/paths/scalping/chapter-02-charts-101/level-08-2.yaml';
import f71 from '../content/paths/scalping/chapter-02-charts-101/level-08-3.yaml';
import f72 from '../content/paths/scalping/chapter-02-charts-101/level-09-1.yaml';
import f73 from '../content/paths/scalping/chapter-02-charts-101/level-09-2.yaml';
import f74 from '../content/paths/scalping/chapter-02-charts-101/level-09-3.yaml';
import f75 from '../content/paths/scalping/chapter-02-charts-101/level-09-4.yaml';
import f76 from '../content/paths/scalping/chapter-02-charts-101/level-10-1.yaml';
import f77 from '../content/paths/scalping/chapter-02-charts-101/level-10-2.yaml';
import f78 from '../content/paths/scalping/chapter-02-charts-101/level-10-3.yaml';
import f79 from '../content/paths/scalping/chapter-02-charts-101/level-11-1.yaml';
import f80 from '../content/paths/scalping/chapter-02-charts-101/level-11-2.yaml';
import f81 from '../content/paths/scalping/chapter-02-charts-101/level-12-1.yaml';
import f82 from '../content/paths/scalping/chapter-02-charts-101/level-13-1.yaml';
import f83 from '../content/paths/scalping/chapter-02-charts-101/level-13-2.yaml';
import f84 from '../content/paths/scalping/chapter-02-charts-101/level-13-3.yaml';
import f85 from '../content/paths/scalping/chapter-02-charts-101/level-13-4.yaml';
import f86 from '../content/paths/scalping/chapter-02-charts-101/level-14-1.yaml';
import f87 from '../content/paths/scalping/chapter-02-charts-101/level-14-2.yaml';
import f88 from '../content/paths/scalping/chapter-02-charts-101/level-14-3.yaml';
import f89 from '../content/paths/scalping/chapter-02-charts-101/level-15-1.yaml';
import f90 from '../content/paths/scalping/chapter-02-charts-101/level-15-2.yaml';
import f91 from '../content/paths/scalping/chapter-02-charts-101/level-16-1.yaml';
import f92 from '../content/paths/scalping/chapter-02-charts-101/level-16-2.yaml';
import f93 from '../content/paths/scalping/chapter-02-charts-101/level-16-3.yaml';
import f94 from '../content/paths/scalping/chapter-02-charts-101/level-17-1.yaml';
import f95 from '../content/paths/scalping/chapter-02-charts-101/level-17-2.yaml';
import f96 from '../content/paths/scalping/chapter-02-charts-101/level-18-1.yaml';
import f97 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-01-1.yaml';
import f98 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-01-2.yaml';
import f99 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-01-3.yaml';
import f100 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-01-4.yaml';
import f101 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-02-1.yaml';
import f102 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-02-2.yaml';
import f103 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-02-3.yaml';
import f104 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-03-1.yaml';
import f105 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-03-2.yaml';
import f106 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-03-3.yaml';
import f107 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-04-1.yaml';
import f108 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-04-2.yaml';
import f109 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-05-1.yaml';
import f110 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-06-1.yaml';
import f111 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-06-2.yaml';
import f112 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-06-3.yaml';
import f113 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-06-4.yaml';
import f114 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-07-1.yaml';
import f115 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-07-2.yaml';
import f116 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-07-3.yaml';
import f117 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-08-1.yaml';
import f118 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-08-2.yaml';
import f119 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-09-1.yaml';
import f120 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-09-2.yaml';
import f121 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-09-3.yaml';
import f122 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-09-4.yaml';
import f123 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-10-1.yaml';
import f124 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-10-2.yaml';
import f125 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-10-3.yaml';
import f126 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-10-4.yaml';
import f127 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-11-1.yaml';
import f128 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-11-2.yaml';
import f129 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-12-1.yaml';
import f130 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-13-1.yaml';
import f131 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-13-2.yaml';
import f132 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-13-3.yaml';
import f133 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-14-1.yaml';
import f134 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-14-2.yaml';
import f135 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-14-3.yaml';
import f136 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-15-1.yaml';
import f137 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-15-2.yaml';
import f138 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-15-3.yaml';
import f139 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-16-1.yaml';
import f140 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-16-2.yaml';
import f141 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-17-1.yaml';
import f142 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-17-2.yaml';
import f143 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-17-3.yaml';
import f144 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-18-1.yaml';
import f145 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-18-2.yaml';
import f146 from '../content/paths/scalping/chapter-03-orders-costs-position-size/level-19-1.yaml';
import f147 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-01-1.yaml';
import f148 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-01-2.yaml';
import f149 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-01-3.yaml';
import f150 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-01-4.yaml';
import f151 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-02-1.yaml';
import f152 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-02-2.yaml';
import f153 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-02-3.yaml';
import f154 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-03-1.yaml';
import f155 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-03-2.yaml';
import f156 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-03-3.yaml';
import f157 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-03-4.yaml';
import f158 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-04-1.yaml';
import f159 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-04-2.yaml';
import f160 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-05-1.yaml';
import f161 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-06-1.yaml';
import f162 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-06-2.yaml';
import f163 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-06-3.yaml';
import f164 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-06-4.yaml';
import f165 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-07-1.yaml';
import f166 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-07-2.yaml';
import f167 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-07-3.yaml';
import f168 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-08-1.yaml';
import f169 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-09-1.yaml';
import f170 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-09-2.yaml';
import f171 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-09-3.yaml';
import f172 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-10-1.yaml';
import f173 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-10-2.yaml';
import f174 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-10-3.yaml';
import f175 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-11-1.yaml';
import f176 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-11-2.yaml';
import f177 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-11-3.yaml';
import f178 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-12-1.yaml';
import f179 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-12-2.yaml';
import f180 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-12-3.yaml';
import f181 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-12-4.yaml';
import f182 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-13-1.yaml';
import f183 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-13-2.yaml';
import f184 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-14-1.yaml';
import f185 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-14-2.yaml';
import f186 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-14-3.yaml';
import f187 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-15-1.yaml';
import f188 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-15-2.yaml';
import f189 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-15-3.yaml';
import f190 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-16-1.yaml';
import f191 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-16-2.yaml';
import f192 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-17-1.yaml';
import f193 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-17-2.yaml';
import f194 from '../content/paths/scalping/chapter-04-reading-fast-markets/level-18-1.yaml';
import f195 from '../content/paths/scalping/chapter-05-finding-the-trade/level-01-1.yaml';
import f196 from '../content/paths/scalping/chapter-05-finding-the-trade/level-01-2.yaml';
import f197 from '../content/paths/scalping/chapter-05-finding-the-trade/level-01-3.yaml';
import f198 from '../content/paths/scalping/chapter-05-finding-the-trade/level-01-4.yaml';
import f199 from '../content/paths/scalping/chapter-05-finding-the-trade/level-02-1.yaml';
import f200 from '../content/paths/scalping/chapter-05-finding-the-trade/level-02-2.yaml';
import f201 from '../content/paths/scalping/chapter-05-finding-the-trade/level-02-3.yaml';
import f202 from '../content/paths/scalping/chapter-05-finding-the-trade/level-02-4.yaml';
import f203 from '../content/paths/scalping/chapter-05-finding-the-trade/level-03-1.yaml';
import f204 from '../content/paths/scalping/chapter-05-finding-the-trade/level-03-2.yaml';
import f205 from '../content/paths/scalping/chapter-05-finding-the-trade/level-03-3.yaml';
import f206 from '../content/paths/scalping/chapter-05-finding-the-trade/level-04-1.yaml';
import f207 from '../content/paths/scalping/chapter-05-finding-the-trade/level-04-2.yaml';
import f208 from '../content/paths/scalping/chapter-05-finding-the-trade/level-05-1.yaml';
import f209 from '../content/paths/scalping/chapter-05-finding-the-trade/level-06-1.yaml';
import f210 from '../content/paths/scalping/chapter-05-finding-the-trade/level-06-2.yaml';
import f211 from '../content/paths/scalping/chapter-05-finding-the-trade/level-06-3.yaml';
import f212 from '../content/paths/scalping/chapter-05-finding-the-trade/level-06-4.yaml';
import f213 from '../content/paths/scalping/chapter-05-finding-the-trade/level-07-1.yaml';
import f214 from '../content/paths/scalping/chapter-05-finding-the-trade/level-07-2.yaml';
import f215 from '../content/paths/scalping/chapter-05-finding-the-trade/level-07-3.yaml';
import f216 from '../content/paths/scalping/chapter-05-finding-the-trade/level-08-1.yaml';
import f217 from '../content/paths/scalping/chapter-05-finding-the-trade/level-08-2.yaml';
import f218 from '../content/paths/scalping/chapter-05-finding-the-trade/level-08-3.yaml';
import f219 from '../content/paths/scalping/chapter-05-finding-the-trade/level-09-1.yaml';
import f220 from '../content/paths/scalping/chapter-05-finding-the-trade/level-09-2.yaml';
import f221 from '../content/paths/scalping/chapter-05-finding-the-trade/level-10-1.yaml';
import f222 from '../content/paths/scalping/chapter-05-finding-the-trade/level-11-1.yaml';
import f223 from '../content/paths/scalping/chapter-05-finding-the-trade/level-11-2.yaml';
import f224 from '../content/paths/scalping/chapter-05-finding-the-trade/level-11-3.yaml';
import f225 from '../content/paths/scalping/chapter-05-finding-the-trade/level-12-1.yaml';
import f226 from '../content/paths/scalping/chapter-05-finding-the-trade/level-12-2.yaml';
import f227 from '../content/paths/scalping/chapter-05-finding-the-trade/level-12-3.yaml';
import f228 from '../content/paths/scalping/chapter-05-finding-the-trade/level-13-1.yaml';
import f229 from '../content/paths/scalping/chapter-05-finding-the-trade/level-13-2.yaml';
import f230 from '../content/paths/scalping/chapter-05-finding-the-trade/level-13-3.yaml';
import f231 from '../content/paths/scalping/chapter-05-finding-the-trade/level-13-4.yaml';
import f232 from '../content/paths/scalping/chapter-05-finding-the-trade/level-14-1.yaml';
import f233 from '../content/paths/scalping/chapter-05-finding-the-trade/level-14-2.yaml';
import f234 from '../content/paths/scalping/chapter-05-finding-the-trade/level-15-1.yaml';
import f235 from '../content/paths/scalping/chapter-05-finding-the-trade/level-15-2.yaml';
import f236 from '../content/paths/scalping/chapter-05-finding-the-trade/level-15-3.yaml';
import f237 from '../content/paths/scalping/chapter-05-finding-the-trade/level-16-1.yaml';
import f238 from '../content/paths/scalping/chapter-05-finding-the-trade/level-16-2.yaml';
import f239 from '../content/paths/scalping/chapter-05-finding-the-trade/level-17-1.yaml';
import f240 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-01-1.yaml';
import f241 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-01-2.yaml';
import f242 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-01-3.yaml';
import f243 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-01-4.yaml';
import f244 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-02-1.yaml';
import f245 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-02-2.yaml';
import f246 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-02-3.yaml';
import f247 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-02-4.yaml';
import f248 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-03-1.yaml';
import f249 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-03-2.yaml';
import f250 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-03-3.yaml';
import f251 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-03-4.yaml';
import f252 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-04-1.yaml';
import f253 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-04-2.yaml';
import f254 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-05-1.yaml';
import f255 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-06-1.yaml';
import f256 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-06-2.yaml';
import f257 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-06-3.yaml';
import f258 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-06-4.yaml';
import f259 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-07-1.yaml';
import f260 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-07-2.yaml';
import f261 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-07-3.yaml';
import f262 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-08-1.yaml';
import f263 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-08-2.yaml';
import f264 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-09-1.yaml';
import f265 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-09-2.yaml';
import f266 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-09-3.yaml';
import f267 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-10-1.yaml';
import f268 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-11-1.yaml';
import f269 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-11-2.yaml';
import f270 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-11-3.yaml';
import f271 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-12-1.yaml';
import f272 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-12-2.yaml';
import f273 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-12-3.yaml';
import f274 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-13-1.yaml';
import f275 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-13-2.yaml';
import f276 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-13-3.yaml';
import f277 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-14-1.yaml';
import f278 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-14-2.yaml';
import f279 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-15-1.yaml';
import f280 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-15-2.yaml';
import f281 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-15-3.yaml';
import f282 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-16-1.yaml';
import f283 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-16-2.yaml';
import f284 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-16-3.yaml';
import f285 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-17-1.yaml';
import f286 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-17-2.yaml';
import f287 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-17-3.yaml';
import f288 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-18-1.yaml';
import f289 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-18-2.yaml';
import f290 from '../content/paths/scalping/chapter-06-risk-and-psychology/level-19-1.yaml';
import f291 from '../content/paths/scalping/chapter-07-scalping-playbook/level-01-1.yaml';
import f292 from '../content/paths/scalping/chapter-07-scalping-playbook/level-01-2.yaml';
import f293 from '../content/paths/scalping/chapter-07-scalping-playbook/level-01-3.yaml';
import f294 from '../content/paths/scalping/chapter-07-scalping-playbook/level-02-1.yaml';
import f295 from '../content/paths/scalping/chapter-07-scalping-playbook/level-02-2.yaml';
import f296 from '../content/paths/scalping/chapter-07-scalping-playbook/level-02-3.yaml';
import f297 from '../content/paths/scalping/chapter-07-scalping-playbook/level-02-4.yaml';
import f298 from '../content/paths/scalping/chapter-07-scalping-playbook/level-03-1.yaml';
import f299 from '../content/paths/scalping/chapter-07-scalping-playbook/level-03-2.yaml';
import f300 from '../content/paths/scalping/chapter-07-scalping-playbook/level-03-3.yaml';
import f301 from '../content/paths/scalping/chapter-07-scalping-playbook/level-03-4.yaml';
import f302 from '../content/paths/scalping/chapter-07-scalping-playbook/level-04-1.yaml';
import f303 from '../content/paths/scalping/chapter-07-scalping-playbook/level-04-2.yaml';
import f304 from '../content/paths/scalping/chapter-07-scalping-playbook/level-04-3.yaml';
import f305 from '../content/paths/scalping/chapter-07-scalping-playbook/level-04-4.yaml';
import f306 from '../content/paths/scalping/chapter-07-scalping-playbook/level-05-1.yaml';
import f307 from '../content/paths/scalping/chapter-07-scalping-playbook/level-06-1.yaml';
import f308 from '../content/paths/scalping/chapter-07-scalping-playbook/level-06-2.yaml';
import f309 from '../content/paths/scalping/chapter-07-scalping-playbook/level-06-3.yaml';
import f310 from '../content/paths/scalping/chapter-07-scalping-playbook/level-06-4.yaml';
import f311 from '../content/paths/scalping/chapter-07-scalping-playbook/level-07-1.yaml';
import f312 from '../content/paths/scalping/chapter-07-scalping-playbook/level-07-2.yaml';
import f313 from '../content/paths/scalping/chapter-07-scalping-playbook/level-07-3.yaml';
import f314 from '../content/paths/scalping/chapter-07-scalping-playbook/level-08-1.yaml';
import f315 from '../content/paths/scalping/chapter-07-scalping-playbook/level-08-2.yaml';
import f316 from '../content/paths/scalping/chapter-07-scalping-playbook/level-09-1.yaml';
import f317 from '../content/paths/scalping/chapter-07-scalping-playbook/level-10-1.yaml';
import f318 from '../content/paths/scalping/chapter-07-scalping-playbook/level-10-2.yaml';
import f319 from '../content/paths/scalping/chapter-07-scalping-playbook/level-10-3.yaml';
import f320 from '../content/paths/scalping/chapter-07-scalping-playbook/level-11-1.yaml';
import f321 from '../content/paths/scalping/chapter-07-scalping-playbook/level-11-2.yaml';
import f322 from '../content/paths/scalping/chapter-07-scalping-playbook/level-11-3.yaml';
import f323 from '../content/paths/scalping/chapter-07-scalping-playbook/level-12-1.yaml';
import f324 from '../content/paths/scalping/chapter-07-scalping-playbook/level-12-2.yaml';
import f325 from '../content/paths/scalping/chapter-07-scalping-playbook/level-12-3.yaml';
import f326 from '../content/paths/scalping/chapter-07-scalping-playbook/level-13-1.yaml';
import f327 from '../content/paths/scalping/chapter-07-scalping-playbook/level-13-2.yaml';
import f328 from '../content/paths/scalping/chapter-07-scalping-playbook/level-14-1.yaml';
import f329 from '../content/paths/scalping/chapter-07-scalping-playbook/level-14-2.yaml';
import f330 from '../content/paths/scalping/chapter-07-scalping-playbook/level-14-3.yaml';
import f331 from '../content/paths/scalping/chapter-07-scalping-playbook/level-15-1.yaml';
import f332 from '../content/paths/scalping/chapter-07-scalping-playbook/level-15-2.yaml';
import f333 from '../content/paths/scalping/chapter-07-scalping-playbook/level-16-1.yaml';
import f334 from '../content/paths/scalping/chapter-07-scalping-playbook/level-16-2.yaml';
import f335 from '../content/paths/scalping/chapter-07-scalping-playbook/level-17-1.yaml';
import f336 from '../content/paths/scalping/chapter-07-scalping-playbook/level-17-2.yaml';
import f337 from '../content/paths/scalping/chapter-07-scalping-playbook/level-17-3.yaml';
import f338 from '../content/paths/scalping/chapter-07-scalping-playbook/level-18-1.yaml';
import f339 from '../content/paths/scalping/chapter-07-scalping-playbook/level-18-2.yaml';
import f340 from '../content/paths/scalping/chapter-07-scalping-playbook/level-19-1.yaml';
import f341 from '../content/paths/scalping/chapter-08-the-trading-day/level-01-1.yaml';
import f342 from '../content/paths/scalping/chapter-08-the-trading-day/level-01-2.yaml';
import f343 from '../content/paths/scalping/chapter-08-the-trading-day/level-01-3.yaml';
import f344 from '../content/paths/scalping/chapter-08-the-trading-day/level-01-4.yaml';
import f345 from '../content/paths/scalping/chapter-08-the-trading-day/level-02-1.yaml';
import f346 from '../content/paths/scalping/chapter-08-the-trading-day/level-02-2.yaml';
import f347 from '../content/paths/scalping/chapter-08-the-trading-day/level-02-3.yaml';
import f348 from '../content/paths/scalping/chapter-08-the-trading-day/level-03-1.yaml';
import f349 from '../content/paths/scalping/chapter-08-the-trading-day/level-03-2.yaml';
import f350 from '../content/paths/scalping/chapter-08-the-trading-day/level-04-1.yaml';
import f351 from '../content/paths/scalping/chapter-08-the-trading-day/level-04-2.yaml';
import f352 from '../content/paths/scalping/chapter-08-the-trading-day/level-04-3.yaml';
import f353 from '../content/paths/scalping/chapter-08-the-trading-day/level-04-4.yaml';
import f354 from '../content/paths/scalping/chapter-08-the-trading-day/level-05-1.yaml';
import f355 from '../content/paths/scalping/chapter-08-the-trading-day/level-06-1.yaml';
import f356 from '../content/paths/scalping/chapter-08-the-trading-day/level-06-2.yaml';
import f357 from '../content/paths/scalping/chapter-08-the-trading-day/level-06-3.yaml';
import f358 from '../content/paths/scalping/chapter-08-the-trading-day/level-07-1.yaml';
import f359 from '../content/paths/scalping/chapter-08-the-trading-day/level-07-2.yaml';
import f360 from '../content/paths/scalping/chapter-08-the-trading-day/level-07-3.yaml';
import f361 from '../content/paths/scalping/chapter-08-the-trading-day/level-08-1.yaml';
import f362 from '../content/paths/scalping/chapter-08-the-trading-day/level-08-2.yaml';
import f363 from '../content/paths/scalping/chapter-08-the-trading-day/level-08-3.yaml';
import f364 from '../content/paths/scalping/chapter-08-the-trading-day/level-09-1.yaml';
import f365 from '../content/paths/scalping/chapter-08-the-trading-day/level-09-2.yaml';
import f366 from '../content/paths/scalping/chapter-08-the-trading-day/level-09-3.yaml';
import f367 from '../content/paths/scalping/chapter-08-the-trading-day/level-10-1.yaml';
import f368 from '../content/paths/scalping/chapter-08-the-trading-day/level-11-1.yaml';
import f369 from '../content/paths/scalping/chapter-08-the-trading-day/level-11-2.yaml';
import f370 from '../content/paths/scalping/chapter-08-the-trading-day/level-11-3.yaml';
import f371 from '../content/paths/scalping/chapter-08-the-trading-day/level-11-4.yaml';
import f372 from '../content/paths/scalping/chapter-08-the-trading-day/level-12-1.yaml';
import f373 from '../content/paths/scalping/chapter-08-the-trading-day/level-12-2.yaml';
import f374 from '../content/paths/scalping/chapter-08-the-trading-day/level-12-3.yaml';
import f375 from '../content/paths/scalping/chapter-08-the-trading-day/level-13-1.yaml';
import f376 from '../content/paths/scalping/chapter-08-the-trading-day/level-13-2.yaml';
import f377 from '../content/paths/scalping/chapter-08-the-trading-day/level-14-1.yaml';
import f378 from '../content/paths/scalping/chapter-08-the-trading-day/level-14-2.yaml';
import f379 from '../content/paths/scalping/chapter-08-the-trading-day/level-14-3.yaml';
import f380 from '../content/paths/scalping/chapter-08-the-trading-day/level-14-4.yaml';
import f381 from '../content/paths/scalping/chapter-08-the-trading-day/level-15-1.yaml';
import f382 from '../content/paths/scalping/chapter-08-the-trading-day/level-15-2.yaml';
import f383 from '../content/paths/scalping/chapter-08-the-trading-day/level-15-3.yaml';
import f384 from '../content/paths/scalping/chapter-08-the-trading-day/level-16-1.yaml';
import f385 from '../content/paths/scalping/chapter-08-the-trading-day/level-16-2.yaml';
import f386 from '../content/paths/scalping/chapter-08-the-trading-day/level-16-3.yaml';
import f387 from '../content/paths/scalping/chapter-08-the-trading-day/level-17-1.yaml';

/**
 * Every chapter folder under content/, in map order, with its sub-level files
 * in play order and its bonus side lessons by the level they follow.
 */
export const CHAPTER_FILES: {
  path: string;
  folder: string;
  files: unknown[];
  bonus: unknown[];
}[] = [
  {
    path: 'all',
    folder: 'shared/chapter-01-market-basics',
    files: [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26, f27, f28, f29, f30, f31, f32, f33, f34, f35, f36, f37, f38, f39, f40, f41, f42, f43, f44, f45, f46, f47],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-02-charts-101',
    files: [f48, f49, f50, f51, f52, f53, f54, f55, f56, f57, f58, f59, f60, f61, f62, f63, f64, f65, f66, f67, f68, f69, f70, f71, f72, f73, f74, f75, f76, f77, f78, f79, f80, f81, f82, f83, f84, f85, f86, f87, f88, f89, f90, f91, f92, f93, f94, f95, f96],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-03-orders-costs-position-size',
    files: [f97, f98, f99, f100, f101, f102, f103, f104, f105, f106, f107, f108, f109, f110, f111, f112, f113, f114, f115, f116, f117, f118, f119, f120, f121, f122, f123, f124, f125, f126, f127, f128, f129, f130, f131, f132, f133, f134, f135, f136, f137, f138, f139, f140, f141, f142, f143, f144, f145, f146],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-04-reading-fast-markets',
    files: [f147, f148, f149, f150, f151, f152, f153, f154, f155, f156, f157, f158, f159, f160, f161, f162, f163, f164, f165, f166, f167, f168, f169, f170, f171, f172, f173, f174, f175, f176, f177, f178, f179, f180, f181, f182, f183, f184, f185, f186, f187, f188, f189, f190, f191, f192, f193, f194],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-05-finding-the-trade',
    files: [f195, f196, f197, f198, f199, f200, f201, f202, f203, f204, f205, f206, f207, f208, f209, f210, f211, f212, f213, f214, f215, f216, f217, f218, f219, f220, f221, f222, f223, f224, f225, f226, f227, f228, f229, f230, f231, f232, f233, f234, f235, f236, f237, f238, f239],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-06-risk-and-psychology',
    files: [f240, f241, f242, f243, f244, f245, f246, f247, f248, f249, f250, f251, f252, f253, f254, f255, f256, f257, f258, f259, f260, f261, f262, f263, f264, f265, f266, f267, f268, f269, f270, f271, f272, f273, f274, f275, f276, f277, f278, f279, f280, f281, f282, f283, f284, f285, f286, f287, f288, f289, f290],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-07-scalping-playbook',
    files: [f291, f292, f293, f294, f295, f296, f297, f298, f299, f300, f301, f302, f303, f304, f305, f306, f307, f308, f309, f310, f311, f312, f313, f314, f315, f316, f317, f318, f319, f320, f321, f322, f323, f324, f325, f326, f327, f328, f329, f330, f331, f332, f333, f334, f335, f336, f337, f338, f339, f340],
    bonus: [],
  },
  {
    path: 'scalping',
    folder: 'paths/scalping/chapter-08-the-trading-day',
    files: [f341, f342, f343, f344, f345, f346, f347, f348, f349, f350, f351, f352, f353, f354, f355, f356, f357, f358, f359, f360, f361, f362, f363, f364, f365, f366, f367, f368, f369, f370, f371, f372, f373, f374, f375, f376, f377, f378, f379, f380, f381, f382, f383, f384, f385, f386, f387],
    bonus: [],
  },
];

/** content/glossary.yaml, once stage GLOSSARY has written it. */
export const GLOSSARY: unknown = null;
